[project]
name = "search-server"
version = "0.1.0"
description = ""
authors = [
    {name = "Shubham Patil",email = "shubhampatilsd@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi (>=0.115.6,<0.116.0)",
    "chromadb (>=0.6.2,<0.7.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
